//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Open_Library_Kashmir.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Donation
    {
        [Display(Name = "Donation ID")]
        public int Donation_ID { get; set; }

        [Display(Name = "Book ID")]
        public int Book_ID { get; set; }

        [Display(Name = "Donor ID")]
        public int Donor_ID { get; set; }

        [Display(Name = "Date Donated")]
        public System.DateTime Date_Donated { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual Donor Donor { get; set; }
    }
}
