//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Open_Library_Kashmir.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Donation
    {
        public int donation_id { get; set; }
        public int book_id { get; set; }
        public int donor_id { get; set; }
        public System.DateTime date_donated { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual Donor Donor { get; set; }
    }
}
