//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Open_Library_Kashmir.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recipient
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Recipient()
        {
            this.Distributions = new HashSet<Distribution>();
        }
    
        public int recipient_id { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string contact_email { get; set; }
        public string contact_phone { get; set; }
        public string address { get; set; }
        public byte[] aadhar_card { get; set; }
        public string remarks { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Distribution> Distributions { get; set; }
    }
}
