// <auto-generated />
namespace Open_Library_Kashmir.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class _202402281612_AddAddressTableLinkItWithUsersAndAddNewColumnsToUsers : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_202402281612_AddAddressTableLinkItWithUsersAndAddNewColumnsToUsers));
        
        string IMigrationMetadata.Id
        {
            get { return "202402281045340_202402281612_AddAddressTableLinkItWithUsersAndAddNewColumnsToUsers"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
