// <auto-generated />
namespace Open_Library_Kashmir.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class TestAzureDatabaseMigration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TestAzureDatabaseMigration));
        
        string IMigrationMetadata.Id
        {
            get { return "202403092028337_TestAzureDatabaseMigration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
